name: Build

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      
      - name: Setup JAVA 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.242' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - run: java -version
        
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
          gradle-version: 6.2
